apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamflix-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: streamflix
  template:
    metadata:
      labels:
        app: streamflix
    spec:
      containers:
      - name: streamflix
        image: atiqacr007.azurecr.io/streamflix:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
