apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:
  name: streamflix-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - www.taremaanki.click  # <--- SIRF domain name, http:// nahi
    secretName: streamflix-tls-secret
  rules:
  - host: www.taremaanki.click # <--- SIRF domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamflix-service
            port:
              number: 80