apiVersion: v1
kind: Service
metadata:
  name: streamflix-service
  namespace: default  # <--- THIS IS THE FIX
  labels:
    app: streamflix
spec:
  type: ClusterIP 
  selector:
    app: streamflix
  ports:
    - name: web
      port: 80
      targetPort: 80