apiVersion: v1
kind: Service
metadata:
  name: streamflix-service
  labels:
    app: streamflix
spec:
  type: ClusterIP 
  selector:
    app: streamflix
  ports:
    - name: metrics
      port: 80
      targetPort: 80
