apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamflix-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    # Ensure redirect is false so it doesn't force you to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: taremaanki.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamflix-service
            port:
              number: 80
  - host: www.taremaanki.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamflix-service
            port:
              number: 80